apiVersion: apps/v1
kind: Deployment
metadata:
  name: lucky-api
  namespace: training
  labels:
    name: lucky-api-deployment
spec:
  selector:
    matchLabels:
      app: lucky-api
  template:
    metadata:
      labels:
        app: lucky-api
    spec:
      imagePullSecrets:
      - name: zregcred
      containers:
      - name: lucky-api
        image: zenigmatraining.azurecr.io/soitron/lucky-api:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        env:
        - name: CONFIG_PATH
          value: /etc/lucky/config.json
        - name: LOG_PATH
          value: /log/current.txt
        volumeMounts:
        - name: lucky-volume
          mountPath: "/etc/lucky/"
        - name: lucky-persistent-volume
          mountPath: "/log/"
      volumes:
      - name: lucky-volume
        configMap:
          name: lucky-api-config
      - name: lucky-persistent-volume
        persistentVolumeClaim:
          claimName: "lucky-pv"