apiVersion: v1
kind: PersistentVolume
metadata:
  name: lucky-pv
spec:
  capacity:
    storage: 1GB
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: gp2-csi
